<!--
SPDX-FileCopyrightText: Sami Finnilä <sami.finnila@nextcloud.com>
SPDX-License-Identifier: AGPL-3.0-or-later
-->
<template>
	<div class="gptfreeprompt-picker-content-wrapper">
		<div v-if="!pickerEnabled" class="gptfreeprompt-picker-content">
			<h2>
				{{ t('gptfreeprompt', 'ERROR: No free prompt provider available') }}
			</h2>
		</div>
		<div v-if="pickerEnabled" class="gptfreeprompt-picker-content">
			<h2>
				{{ t('gptfreeprompt', 'AI text generation') }}
			</h2>
			<div class="input-wrapper">
				<NcTextField
					ref="gptfreeprompt-search-input"
					:value.sync="query"
					:label="inputPlaceholder"
					:disabled="loading"
					:show-trailing-button="!!query"
					@keydown.enter="generate"
					@trailing-button-click="query = ''" />
			</div>
			<div v-if="result === null || query === ''"
				class="prompts">
				<NcUserBubble v-for="p in prompts"
					:key="p.id + p.value"
					class="prompt-bubble"
					:title="p.value"
					:size="30"
					avatar-image="icon-history"
					:display-name="p.value"
					@click="query = p.value" />
			</div>
			<div>
				<GptFreePromptGenerationDisplay v-if="genId !== null"
					:gen-id="genId"
					:result.sync="result"
					@error="onError"
					@loaded="onLoaded" />
			</div>
			<div class="footer">
				<NcButton class="advanced-button"
					type="tertiary"
					:aria-label="t('gptfreeprompt', 'Show/hide advanced options')"
					@click="showAdvanced = !showAdvanced">
					<template #icon>
						<component :is="showAdvancedIcon" />
					</template>
					{{ t('gptfreeprompt', 'Advanced options') }}
				</NcButton>
				<NcButton
					type="secondary"
					:aria-label="t('gptfreeprompt', 'Preview text generation by AI')"
					:disabled="loading || !query"
					@click="generate">
					{{ previewButtonLabel }}
					<template #icon>
						<NcLoadingIcon v-if="loading" />
						<RefreshIcon v-else-if="result !== null" />
						<EyeIcon v-else />
					</template>
				</NcButton>
				<NcButton v-if="genId !== null && loading"
					type="secondary"
					@click="notifyWhenReady">
					{{ t('gptfreeprompt', 'Notify when ready') }}
					<template #icon>
						<ArrowRightIcon />
					</template>
				</NcButton>
				<NcButton v-if="result !== null"
					type="primary"
					:aria-label="t('gptfreeprompt', 'Submit text generated by AI')"
					:disabled="loading || emptyResult"
					@click="submit">
					{{ t('gptfreeprompt', 'Done') }}
					<template #icon>
						<ArrowRightIcon />
					</template>
				</NcButton>
			</div>
			<div v-show="showAdvanced" class="advanced">
				<div class="line">
					<label for="nb-results">
						{{ t('gptfreeprompt', 'How many results to generate') }}
					</label>
					<div class="spacer" />
					<input
						id="nb-results"
						v-model="completionNumber"
						type="number"
						min="1"
						max="10"
						step="1">
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import EyeIcon from 'vue-material-design-icons/Eye.vue'
import RefreshIcon from 'vue-material-design-icons/Refresh.vue'
import ArrowRightIcon from 'vue-material-design-icons/ArrowRight.vue'
import ChevronRightIcon from 'vue-material-design-icons/ChevronRight.vue'
import ChevronDownIcon from 'vue-material-design-icons/ChevronDown.vue'
import HelpCircleIcon from 'vue-material-design-icons/HelpCircle.vue'

import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
import NcTextField from '@nextcloud/vue/dist/Components/NcTextField.js'
import NcSelect from '@nextcloud/vue/dist/Components/NcSelect.js'
import NcCheckboxRadioSwitch from '@nextcloud/vue/dist/Components/NcCheckboxRadioSwitch.js'
import NcUserBubble from '@nextcloud/vue/dist/Components/NcUserBubble.js'

import GptFreePromptGenerationDisplay from '../components/GptFreePromptGenerationDisplay.vue'

import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { showError, showMessage } from '@nextcloud/dialogs'

export default {
	name: 'GptFreePromptCustomPickerElement',

	components: {
		NcButton,
		NcLoadingIcon,
		NcTextField,
		NcSelect,
		NcCheckboxRadioSwitch,
		ChevronRightIcon,
		ChevronDownIcon,
		HelpCircleIcon,
		ArrowRightIcon,
		NcUserBubble,
		RefreshIcon,
		EyeIcon,
		GptFreePromptGenerationDisplay,
	},

	props: {
		providerId: {
			type: String,
			required: true,
		},
		accessible: {
			type: Boolean,
			default: false,
		},
		pickerEnabled: {
			type: Boolean,
			default: true,
		},
	},

	data() {
		return {
			query: '',
			genId: null,
			loading: false,
			error: false,
			models: [],
			inputPlaceholder: t('gptfreeprompt', 'What is the matter with putting pineapple on pizza?'),
			showAdvanced: false,
			completionNumber: 1,
			prompts: null,
			notify: false,
			result: null,
		}
	},

	computed: {
		showAdvancedIcon() {
			return this.showAdvanced
				? ChevronDownIcon
				: ChevronRightIcon
		},
		previewButtonLabel() {
			return this.result !== null
				? t('gptfreeprompt', 'Regenerate')
				: t('gptfreeprompt', 'Preview')
		},
		emptyResult() {
			return this.result.trim() === ''
		},
	},

	watch: {
	},

	mounted() {
		this.focusOnInput()
		this.getPromptHistory()
	},

	beforeDestroy() {
		if (this.genId !== null && !this.notify) {
			this.cancelGeneration()
		}
	},

	methods: {
		focusOnInput() {
			setTimeout(() => {
				this.$refs['gptfreeprompt-search-input'].$el.getElementsByTagName('input')[0]?.focus()
			}, 300)
		},
		getPromptHistory() {
			const params = {
				params: {
				},
			}
			const url = generateUrl('/apps/gptfreeprompt/prompt_history')
			return axios.get(url, params)
				.then((response) => {
					this.prompts = response.data
				})
				.catch((error) => {
					console.error(error)
				})
		},
		submit() {
			this.$emit('submit', this.result.trim())
		},
		onError() {
			this.error = true
			this.loading = false
			this.genId = null
		},
		onLoaded() {
			this.loading = false
		},
		insertPrompt(prompt) {
			if (this.prompts.find(p => p.value === prompt) === undefined) {
				this.prompts.unshift({
					id: 0,
					value: prompt,
				})
			}
		},
		generate() {
			if (this.query === '') {
				return
			}
			this.loading = true
			this.error = false
			this.result = null
			this.genId = null
			const params = {
				prompt: this.query,
				nResults: this.completionNumber,
			}
			const url = generateUrl('/apps/gptfreeprompt/process_prompt')
			return axios.post(url, params)
				.then((response) => {
					const data = response.data
					if (data.length && data.length > 0) {
						this.genId = data

						this.insertPrompt(this.query)
					} else {
						this.error = response.data.error
					}
				})
				.catch((error) => {
					this.loading = false
					console.error('Text  completions request error', error)
					showError(
						t('gptfreeprompt', 'Text generation error') + ': '
							+ (error.response?.data?.body?.error?.message
								|| error.response?.data?.body?.error?.code
								|| error.response?.data?.error
								|| t('gptfreeprompt', 'Unknown text generation API error')
							),
					)
				})
		},
		cancelGeneration() {
			const params = {
				genId: this.genId,
			}
			const url = generateUrl('/apps/gptfreeprompt/cancel_generation')
			return axios.post(url, params)
				.then((response) => {
					this.genId = null
					this.result = null
					this.loading = false
				})
				.catch((error) => {
					console.error('Text  completions request error', error)
					showError(
						t('gptfreeprompt', 'Text generation error') + ': '
							+ (error.response?.data?.body?.error?.message
								|| error.response?.data?.body?.error?.code
								|| error.response?.data?.error
								|| t('gptfreeprompt', 'Unknown text generation API error')
							),
					)
				})
		},
		notifyWhenReady() {
			if (this.failed || this.genId === null) {
				return
			}

			const params = {
				genId: this.genId,
				notify: true,
			}
			const url = generateUrl('/apps/gptfreeprompt/set_notify')
			axios.post(url, params)
				.then(() => {
					showMessage(t('gptfreeprompt', 'You will be notified when the text generation is ready.'))
					this.notify = true
					this.$emit('submit', '')
				})
				.catch((error) => {
					console.error('Notify when ready request error', error)
					showError(
						t('gptfreeprompt', 'Notify when ready error') + ': '
						+ (error.response?.data?.body?.error?.message
							|| error.response?.data?.body?.error?.code
							|| error.response?.data?.error
							|| t('gptfreeprompt', 'Unknown notify when ready error')
						),
					)
				})
		},
	},
}
</script>

<style scoped lang="scss">
.gptfreeprompt-picker-content-wrapper {
	width: 100%;
}

.gptfreeprompt-picker-content {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding: 12px 16px 16px 16px;

	h2 {
		display: flex;
		align-items: center;
	}

	.prompts {
		margin-top: 8px;
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		> * {
			margin-right: 8px;
		}
	}

	.prompt-bubble {
		max-width: 250px;
	}

	.preview {
		width: 100%;
		h3 {
			font-weight: bold;
		}
		.editable-preview {
			width: 100% !important;
			max-height: 300px !important;
		}
	}

	.spacer {
		flex-grow: 1;
	}

	.attribution {
		color: var(--color-text-maxcontrast);
		padding-bottom: 8px;
	}

	.input-wrapper {
		display: flex;
		align-items: center;
		width: 100%;
	}

	.prompt-select {
		width: 100%;
		margin-top: 4px;
	}

	.footer {
		width: 100%;
		display: flex;
		align-items: center;
		justify-content: end;
		margin-top: 12px;
		> * {
			margin-left: 4px;
		}
	}

	.advanced {
		width: 100%;
		padding: 12px 0;
		.line {
			display: flex;
			align-items: center;
			margin-top: 8px;

			input {
				width: 200px;
			}
			.model-select {
				width: 300px;
			}
		}

		input[type=number] {
			width: 120px;
			appearance: initial !important;
			-moz-appearance: initial !important;
			-webkit-appearance: initial !important;
		}
	}
}
</style>
