OC.L10N.register(
    "gptfreeprompt",
    {
    "AI text generation" : "Vytváření textů pomocí AI",
    "A SmartPicker for interfacing with the GPT integrations that provide free prompt cabability" : "Inteligentní výběr pro interakci s napojení na GPT, které poskytuje schopnost dotazování zdarma",
    "A unified SmartPicker for Nextcloud large language model integrations that provide free prompting cabability." : "Sjednocený inteligentní výběr pro napojení Nextcloud na rozsáhlé jazykové modely, který poskytuje schopnost dotazování se zdarma.",
    "ERROR: No free prompt provider available" : "CHYBA: Není k dispozici žádný bezplatný poskytovatel pro dotazy",
    "Preview" : "Náhled",
    "Preview content" : "Zobrazit náhled obsahu",
    "Show/hide advanced options" : "Zobrazit/skrýt pokročilé předvolby",
    "Advanced options" : "Pokročilé předvolby",
    "Preview text generation by AI" : "Náhled vytváření textu pomocí AI",
    "Submit text generated by AI" : "Odeslat text vytvořený pomocí AI",
    "Include the prompt in the result" : "Ve výsledku uvádět i dotazy",
    "How many results to generate" : "Kolik výsledků vytvořit",
    "What is the matter with putting pineapple on pizza?" : "Jaký je smysl toho dávat ananas na pizzu?",
    "Regenerate" : "Znovu vytvořit",
    "Text generation error" : "Chyba vytváření textů",
    "Unknown text generation API error" : "Neznámá chyba API vytváření textů",
    "Prompt" : "Výzva",
    "Result" : "Výsledek",
    "Result {index}" : "Výsledek {index}"
},
"nplurals=4; plural=(n == 1 && n % 1 == 0) ? 0 : (n >= 2 && n <= 4 && n % 1 == 0) ? 1: (n % 1 != 0 ) ? 2 : 3;");
